### PR TITLE
Added Web App Implementation using Flask for storing and displaying user's data 

### PR DESCRIPTION
**Pull request by azlaanmsamad**
Things done :
-Removed and added some new files in this branch just to make the web app simpler to understand.
- The Web app can take user name input (via forms) and store in the database and also display the stored user' name with timestamp but this is done by retrieving data from the database.
- Added MIT License,  Readme file

TO DO:
- Add data from two more sensors
- Add a message broker and Queue
-  REST API "clear" that cleans data in memory

Currently working on:
- In memory database and REST API 'clear' which cleans the in memory data.

### CODE REVIEW

**Comment by pgraverdy** [comment]
Regarding the PR, you should avoid commiting local files (that are only valid on your computer  and may conflict with other's developpers configurations).
Typically, the `.idea` and the `pycache`folders should be excluded. The clean way is to have a `.gitignore`file in the root of the project and add files into it (you can check the syntax in various tutorials).

Pay attention that since you have already pushed a version of these folders in Github, you should not add them right away to the '.gitignore' file. You easiest is to make a copy of these 2 folders  in some tmp folder, delete them in the project, commit the change (the deletion of the 2 folders) on github, then move back from tmp and add to `.gitignore`, then push the .gitignore to github.

**Comment by azlaanmsamad** [comment]
@pgraverdy Thank you for your comment. The `.gitignore ` file is actually present inside the `.idea` folder. This is done as a default by the PyCharm. I will do as recommended.

**Comment by azlaanmsamad** [comment]
@pgraverdy @biswesh456  
I have removed the  `.idea` and  `__pycache__` from the repository and added `.gitignore ` as recommended.
Can you review and merge ?

**Comment by azlaanmsamad** [comment]
@pgraverdy @biswesh456 Can you guys please take a look at the `db_in_memory` branch as well ?
In that branch, you can actually see the 5 latest user's details in the memory with their timestamps. And also you the Clear button to delete all the user's details.

Thanks :)

**Comment by pgraverdy** [comment]
@azlaanmsamad 
ok, the local files (.idea, pycache) are now excluded. This is fine. There was other comments in this PR but I created a separate issue #3 for this. All discussions in this PR are thus closed/moved elsewhere.

**Comment by azlaanmsamad** [comment]
@pgraverdy Thank you.

**Pull request merged**
